### ISSUE TITLE
Maintainer lists use exclusively masculine names

### ISSUE THREAD

**Issue by thenickcox** [lgtmco/lgtm-docs#1]
This looks like a cool project. Thanks for putting it out there.

I noticed that on lgtm.co and [in this repo in the `approvers` docs](https://github.com/lgtmco/lgtm-docs/blob/master/content/approvers.md), the lists of approvers are all traditionally male names. 

It, of course, makes sense that your name would be on there in both cases, but the others appear to be demo data with `@mail.com` email addresses:

![screen shot 2015-12-15 at 1 48 12 pm](https://cloud.githubusercontent.com/assets/702327/11825204/84ae78c4-a332-11e5-83cb-2f76f4a2e200.png)

Granted, they're probably friends and/or colleagues of yours, so it makes sense that they'd be top of mind. But for those unfamiliar with these developers, the names might as well be random.

Would you accept a PR for the `approvers.md` file that adds a few names of women and/or other underrepresented communities in tech? And would you consider adding it to the lgtm.co site?

**Comment by bradrydzewski** [comment]
This file no longer exists, however, I'm happy to accept a pull request that adds a female name to the following section of the docs https://lgtm.co/docs/maintainers/
