### ISSUE TITLE
Self-hosted licencing fee is unclear

### ISSUE THREAD

**Issue by wking** [lgtmco/lgtm-docs#7]
Notes about self-hosting eventually requiring a licensing fee landed in 63afbc69 (added details about enterprise options, 2015-12-08) and were updated in a391a45f (updated docs, 2016-01-19).  We're considering using this project in the Open Container Initiative (opencontainers/runc#916), but wanted clarity on how you see that sort of thing working before committing.  Do you plan to continue to maintain the project under the Apache 2.0 license?  If so, is the “licensing fee” going to be more like a “suggested donation”?  Or is the “licensing fee” actually more like a support contract (i.e. “you can self-host for free, but you can only email me for troubleshooting help if you have a support contract”)?  The “Technical support is only provided to paying account holders…” language from a391a45f suggests the support contract interpretation.  If that is accurate, adjusting the self-hosting phrasing to make it explicit would make me a lot more comfortable ;).

**Comment by bradrydzewski** [comment]
Good catch. The license fee section was written prior to open sourcing the codebase under an Apache2 license, and is now obsolete. I've removed that section from the documentation:
https://github.com/lgtmco/lgtm-docs/commit/25e73dfc126f3b58e5f97e39902401a3bce07962

The docs haven't bee re-published yet (in the middle of a CI upgrade, so auto-publish is disabled) but next time the docs are published they will reflect this change.

**Comment by wking** [comment]
On Wed, Jun 15, 2016 at 10:48:55AM -0700, Brad Rydzewski wrote:

> The license fee section was written prior to open sourcing the
> codebase under an Apache2 license, and is now obsolete.

Ah, wonderful :).  Thanks for the quick response.
